const assert = require("node:assert/strict");
const test = require("node:test");
const { SKIP, openTerminalApp } = require("./support/terminal-clipboard-browser");

async function arrowEvents(page) {
  // The fixture samples cancellation after dispatch in a timer. Input flush
  // completion alone does not guarantee that this observation has run yet.
  await page.waitForFunction(() => clipboardEvents
    .filter(event => event.key?.startsWith("Arrow"))
    .every(event => event.prevented !== undefined));
  return page.evaluate(() => clipboardEvents.filter(event => event.key?.startsWith("Arrow")));
}

for (const platform of ["Linux x86_64", "Win32", "MacIntel"]) {
  test(`Alt vertical arrows preserve modifiers with real xterm on ${platform}`, { skip: SKIP }, async () => {
    const app = await openTerminalApp({ platform });
    try {
      await app.addTab({ provider: "codex" });
      for (const applicationCursor of [false, true]) {
        await app.output(`\x1b[?1${applicationCursor ? "h" : "l"}`);
        for (const [key, data] of [["ArrowUp", "\x1b[1;3A"], ["ArrowDown", "\x1b[1;3B"]]) {
          await app.page.keyboard.press(`Alt+${key}`);
          await app.settle();
          assert.deepEqual(app.inputs.splice(0), [{ path: "/api/terminal/session-agent/input", data }],
            `${key}, application cursor = ${applicationCursor}`);
        }
      }
      assert.deepEqual(app.errors, []);
    } finally { await app.close(); }
  });
}

for (const platform of ["Linux x86_64", "Win32", "MacIntel"]) {
  test(`neighboring arrow shortcuts keep xterm encoding on ${platform}`, { skip: SKIP }, async () => {
    const app = await openTerminalApp({ platform });
    try {
      await app.addTab();
      for (const applicationCursor of [false, true]) {
        await app.output(`\x1b[?1${applicationCursor ? "h" : "l"}`);
        for (const [key, suffix] of [["ArrowUp", "A"], ["ArrowDown", "B"],
          ["ArrowRight", "C"], ["ArrowLeft", "D"]]) {
          for (const [prefix, data] of [
            ["", `\x1b${applicationCursor ? "O" : "["}${suffix}`],
            ["Control+", `\x1b[1;5${suffix}`],
            ["Alt+Control+", `\x1b[1;7${suffix}`],
            ["Alt+Shift+", `\x1b[1;4${suffix}`],
          ]) {
            await app.page.keyboard.press(`${prefix}${key}`);
            await app.settle();
            assert.deepEqual(app.inputs.splice(0), [{ path: "/api/terminal/session-agent/input", data }],
              `${prefix}${key}, application cursor = ${applicationCursor}`);
          }
        }
        for (const [key, data] of [["ArrowLeft", platform === "MacIntel" ? "\x1bb" : "\x1b[1;5D"],
          ["ArrowRight", platform === "MacIntel" ? "\x1bf" : "\x1b[1;5C"]]) {
          await app.page.keyboard.press(`Alt+${key}`);
          await app.settle();
          assert.deepEqual(app.inputs.splice(0), [{ path: "/api/terminal/session-agent/input", data }]);
        }
        await app.page.keyboard.press("Alt+Meta+ArrowUp");
        await app.page.keyboard.press("Alt+Meta+ArrowDown");
        await app.settle();
        assert.deepEqual(app.inputs, []);
      }
      assert.deepEqual(app.errors, []);
    } finally { await app.close(); }
  });
}

test("Alt vertical arrows emit once per keydown including repeat, never on keyup", { skip: SKIP }, async () => {
  const app = await openTerminalApp();
  try {
    await app.addTab();
    for (const [key, data] of [["ArrowUp", "\x1b[1;3A"], ["ArrowDown", "\x1b[1;3B"]]) {
      await app.page.keyboard.down("Alt");
      for (let repeat = 0; repeat < 3; repeat++) {
        await app.page.keyboard.down(key);
        await app.settle();
        assert.deepEqual(app.inputs.splice(0), [{ path: "/api/terminal/session-agent/input", data }]);
      }
      await app.page.keyboard.up(key);
      await app.page.keyboard.up("Alt");
      await app.settle();
      assert.deepEqual(app.inputs, []);
    }
    assert.deepEqual((await arrowEvents(app.page))
      .map(event => [event.trusted, event.prevented]), Array(6).fill([true, true]));
    assert.deepEqual(app.errors, []);
  } finally { await app.close(); }
});

test("composition leaves Alt arrows to xterm without the navigation override", { skip: SKIP }, async () => {
  const app = await openTerminalApp();
  try {
    await app.addTab();
    // IME events cannot be generated by Playwright's keyboard API. Dispatch
    // composing DOM events into the real xterm listener and verify its existing
    // Linux encoding, distinct from the adapter's non-composing Alt encoding.
    for (const [key, keyCode, data] of [["ArrowUp", 38, "\x1b[1;5A"], ["ArrowDown", 40, "\x1b[1;5B"]]) {
      await app.page.evaluate(({ key, keyCode }) => {
        terminalStateFor().term.textarea.dispatchEvent(new KeyboardEvent("keydown", {
          key, keyCode, altKey: true, isComposing: true, bubbles: true, cancelable: true,
        }));
      }, { key, keyCode });
      await app.settle();
      assert.deepEqual(app.inputs.splice(0), [{ path: "/api/terminal/session-agent/input", data }]);
    }
    assert.deepEqual(app.errors, []);
  } finally { await app.close(); }
});

test("outside focus and an open palette keep their own keyboard behavior", { skip: SKIP }, async () => {
  const app = await openTerminalApp();
  try {
    await app.addTab();
    await app.page.evaluate(() => new Promise(requestAnimationFrame));
    await app.page.evaluate(() => {
      const input = document.createElement("textarea");
      input.id = "outside-keyboard";
      document.body.prepend(input);
      input.focus();
    });
    await app.page.keyboard.press("Alt+ArrowUp");
    await app.page.keyboard.press("Alt+ArrowDown");
    await app.settle();
    assert.deepEqual(app.inputs, []);
    assert.deepEqual((await arrowEvents(app.page)).map(event => event.prevented), [false, false]);
    await app.page.keyboard.press("Control+k");
    await app.page.waitForSelector(".command-palette-backdrop");
    await app.page.keyboard.press("Alt+ArrowUp");
    await app.page.keyboard.press("Alt+ArrowDown");
    await app.settle();
    assert.deepEqual(app.inputs, []);
    assert.deepEqual(app.errors, []);
  } finally { await app.close(); }
});

test("retained output consumes Alt arrows after exit or loss of session", { skip: SKIP }, async () => {
  const app = await openTerminalApp();
  try {
    for (const change of ["exit", "session"]) {
      await app.addTab({ id: change });
      await app.output("retained output");
      await app.page.evaluate(change => {
        const terminal = terminalStateFor();
        window.retainedRenderer = terminal.term;
        if (change === "exit") finishTerminalExit(currentToolbarTab(), terminal);
        else terminal.sessionId = "";
        terminal.term.focus();
      }, change);
      await app.page.keyboard.press("Alt+ArrowUp");
      await app.page.keyboard.press("Alt+ArrowDown");
      await app.settle();
      assert.deepEqual(app.inputs, []);
      assert.equal(await app.page.evaluate(() => terminalStateFor().term === retainedRenderer), true);
    }
    assert.deepEqual((await arrowEvents(app.page)).map(event => event.prevented), Array(4).fill(true));
    assert.deepEqual(app.errors, []);
  } finally { await app.close(); }
});

test("Alt arrow input belongs to its originating tab through switching and renderer replacement", { skip: SKIP }, async () => {
  const app = await openTerminalApp();
  try {
    await app.addTab({ id: "first" });
    await app.page.evaluate(() => { window.firstRenderer = terminalStateFor().term; });
    await app.addTab({ id: "second" });
    for (const id of ["first", "second", "first"]) {
      await app.page.evaluate(id => { chatState.activeTabId = id; drawToolbar(); terminalStateFor().term.focus(); }, id);
      await app.page.keyboard.press("Alt+ArrowUp");
      await app.settle();
      assert.deepEqual(app.inputs.splice(0), [{ path: `/api/terminal/session-${id}/input`, data: "\x1b[1;3A" }]);
    }
    assert.equal(await app.page.evaluate(() => terminalStateFor().term === firstRenderer), true);
    // Queue an event and switch before flush in the same task. Delivery stays
    // with the origin even though another renderer has become active.
    await app.page.evaluate(() => {
      terminalStateFor().term.textarea.dispatchEvent(new KeyboardEvent("keydown", {
        key: "ArrowDown", keyCode: 40, altKey: true, bubbles: true, cancelable: true,
      }));
      chatState.activeTabId = "second";
      drawToolbar();
    });
    await app.settle();
    assert.deepEqual(app.inputs.splice(0), [{ path: "/api/terminal/session-first/input", data: "\x1b[1;3B" }]);
    await app.page.evaluate(() => {
      const terminal = terminalStateFor();
      window.oldRenderer = terminal.term;
      window.oldTextarea = terminal.term.textarea;
      terminal.term = null;
      ensureTerminalRenderer(document.querySelector(".terminal-output"));
      terminal.term.focus();
      oldTextarea.dispatchEvent(new KeyboardEvent("keydown", {
        key: "ArrowUp", keyCode: 38, altKey: true, bubbles: true, cancelable: true,
      }));
      oldRenderer.dispose();
    });
    await app.settle();
    assert.deepEqual(app.inputs, [], "old renderer cannot send through its retained key listener");
    await app.page.keyboard.press("Alt+ArrowDown");
    await app.settle();
    assert.deepEqual(app.inputs.splice(0), [{ path: "/api/terminal/session-second/input", data: "\x1b[1;3B" }]);
    assert.deepEqual(app.errors, []);
  } finally { await app.close(); }
});

test("session replacement before flush discards buffered Alt arrows", { skip: SKIP }, async () => {
  const app = await openTerminalApp();
  try {
    await app.addTab();
    await app.page.evaluate(() => {
      const terminal = terminalStateFor();
      terminal.term.textarea.dispatchEvent(new KeyboardEvent("keydown", {
        key: "ArrowUp", keyCode: 38, altKey: true, bubbles: true, cancelable: true,
      }));
      terminal.sessionId = "replacement";
      flushTerminalInput(terminal);
    });
    await app.settle();
    assert.deepEqual(app.inputs, []);
    await app.page.keyboard.press("Alt+ArrowDown");
    await app.settle();
    assert.deepEqual(app.inputs, [{ path: "/api/terminal/replacement/input", data: "\x1b[1;3B" }]);
    assert.deepEqual(app.errors, []);
  } finally { await app.close(); }
});

test("all profiles and provider fixtures preserve Alt arrows and existing control keys", { skip: SKIP }, async () => {
  const app = await openTerminalApp();
  try {
    for (const provider of ["claude", "codex"]) {
      for (const mode of ["terminal", "agent", "plan", "goal", "standalone", "skill"]) {
        const id = `${mode}-${provider}`;
        await app.addTab({ id, mode, provider });
        for (const [key, data] of [["Alt+ArrowUp", "\x1b[1;3A"], ["Alt+ArrowDown", "\x1b[1;3B"],
          ["Control+Enter", "\n"], ["Control+z", mode === "terminal" ? "\x1a" : ""],
          ["Control+k", "\x0b"]]) {
          await app.page.keyboard.press(key);
          await app.settle();
          assert.deepEqual(app.inputs.splice(0), data ? [{ path: `/api/terminal/session-${id}/input`, data }] : [], `${id}: ${key}`);
        }
        assert.equal(await app.page.locator(".command-palette-backdrop").count(), 0);
      }
    }
    assert.deepEqual(app.errors, []);
  } finally { await app.close(); }
});
