/// Node Runtime Config keys copied by the supported copy-between-node action.
pub(super) const RUNTIME_SETTINGS: &[&str] = &[
    "parallel_run_cap",
    "parallel_per_node_cap",
    "parallel_per_provider_cap",
    "parallel_per_target_app_cap",
    "automatic_agent_resource_budget_percent",
    "branch_name_pattern",
    "agent_idle_timeout_seconds",
    "agent_hard_cap_seconds",
    "agent_limit_pause_seconds",
    "worker_memory_limit_mb",
    "ui_memory_limit_mb",
    "worker_cpu_priority",
    "resource_isolation_mode",
    "chat_idle_timeout_seconds",
    "backlog_promote_after_seconds",
    "worktree_cleanup_after_seconds",
    "state_sync_debounce_seconds",
    "state_sync_stale_threshold_seconds",
    "state_sync_auto_recovery",
    "state_sync_agent_resolution",
    "project_update_pulse_interval_seconds",
    "file_browser_ignore_patterns",
    "workflow_conflict_resolution",
    "agent_cli",
];

/// Target App Config keys copied by the same node-scoped action.
pub(super) const APPLICATION_SETTINGS: &[&str] = &[
    "agent_subpath",
    "git_remote",
    "merge_target_branch",
    "target_app_url",
    "target_app_start_instructions",
    "target_app_stop_instructions",
    "target_app_build_instructions",
    "target_app_start_command",
    "target_app_stop_command",
    "target_app_build_command",
    "target_app_test_command",
    "target_app_test_commands",
    "target_app_status_command",
    "target_app_cwd",
    "target_app_env_json",
    "target_app_start_timeout_seconds",
    "target_app_stop_timeout_seconds",
    "target_app_build_timeout_seconds",
    "target_app_test_timeout_seconds",
    "target_app_status_timeout_seconds",
    "target_app_log_path",
    "target_app_http_check_url",
    "target_app_tcp_check_host",
    "target_app_tcp_check_port",
    "target_app_process_check_command",
];
