"""Direct backend method names used by refine_ui and refine_server."""
from __future__ import annotations


M_PING = "ping"
M_PREFLIGHT = "preflight"
M_LAUNCH = "launch"
M_ENFORCE_SCHEDULING = "enforce_scheduling"
M_CANCEL = "cancel"
M_CANCEL_ALL = "cancel_all"
M_VERIFY = "verify"
M_CREATE_GAP = "create_gap"
M_APPEND_ROUND = "append_round"
M_EDIT_ROUND = "edit_round"
M_LOG_APPEND = "log_append"
M_DELETE_GAP = "delete_gap"
M_SET_NOTES = "set_notes"
M_CHAT_START = "chat_start"
M_CHAT_INPUT = "chat_input"
M_CHAT_READ = "chat_read"
M_CHAT_STOP = "chat_stop"
M_RUNNING = "running"
M_DIAGNOSTICS = "diagnostics"
M_EXTRACT_GAPS = "extract_gaps"
M_RENAME_REPORTER = "rename_reporter"
M_RENAME_REPORTER_STRINGS = "rename_reporter_strings"
M_LIST_CHANGES = "list_changes"
M_UNDO_GAP = "undo_gap"
M_GOVERNANCE_GET = "governance_get"
M_GOVERNANCE_SAVE = "governance_save"
M_GOVERNANCE_GENERATE_RULES = "governance_generate_rules"
M_GOVERNANCE_WAKE = "governance_wake"
M_TARGET_APP_RUN = "target_app_run"
M_TARGET_APP_GENERATE = "target_app_generate"
M_TARGET_APP_HEALTH = "target_app_health"
