"""argparse-based CLI for refine.

Subcommands:
- init    — write refine.toml + run/ + gaps/ in a chosen volume root
- runner  — start the host-native runner daemon
- web     — start the webapp (rarely invoked directly; Docker wraps it)
- doctor  — diagnostic snapshot (config, IPC, claude, git)
"""
from __future__ import annotations

import argparse
import json
import os
import shutil
import socket
import subprocess
import sys
from pathlib import Path

from refine_shared import config


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="refine", description="Manage refine.")
    parser.add_argument(
        "--config", "-c",
        help="Path to refine.toml (defaults to walking up from cwd).",
    )
    sub = parser.add_subparsers(dest="command", required=True)

    p_init = sub.add_parser(
        "init",
        help="Initialize refine for a client repo and bind this refine clone to it.",
        description=(
            "Bootstraps a client repo: creates <client>/.refine/refine.toml + "
            "run/ + gaps/, and (when run from a refine source dir) writes a "
            ".refine-binding + .env so subsequent commands target the same "
            "client without arguments."
        ),
    )
    p_init.add_argument(
        "path", nargs="?", default=None,
        help="Path to the client repo. Defaults to cwd (back-compat).",
    )
    p_init.add_argument("--force", action="store_true",
                        help="Overwrite an existing refine.toml / .refine-binding.")
    p_init.set_defaults(fn=cmd_init)

    p_runner = sub.add_parser("runner", help="Start the host runner daemon.")
    p_runner.add_argument(
        "--foreground", "-f", action="store_true",
        help="Stay attached to the terminal instead of detaching. Useful for "
             "debugging and required for systemd Type=simple units.",
    )
    p_runner.set_defaults(fn=cmd_runner)

    p_stop = sub.add_parser(
        "stop",
        help="Stop the host runner daemon if one is running.",
        description=(
            "Reads run/runner.pid from the bound client's .refine/ directory "
            "and sends SIGTERM; falls back to SIGKILL after a timeout."
        ),
    )
    p_stop.add_argument(
        "--timeout", "-t", type=float, default=10.0,
        help="Seconds to wait for graceful exit before SIGKILL (default 10).",
    )
    p_stop.add_argument(
        "--force", action="store_true",
        help="Skip SIGTERM and go straight to SIGKILL.",
    )
    p_stop.set_defaults(fn=cmd_stop)

    p_web = sub.add_parser("web", help="Start the webapp.")
    p_web.set_defaults(fn=cmd_web)

    p_doctor = sub.add_parser("doctor", help="Print a diagnostic snapshot.")
    p_doctor.set_defaults(fn=cmd_doctor)

    args = parser.parse_args(argv)
    return args.fn(args)


# ----- init -------------------------------------------------------------------

def cmd_init(args: argparse.Namespace) -> int:
    cwd = Path.cwd().resolve()
    client_repo = Path(args.path).expanduser().resolve() if args.path else cwd

    if not client_repo.is_dir():
        print(f"refine init: not a directory: {client_repo}", file=sys.stderr)
        return 1
    if not (client_repo / ".git").exists():
        print(
            f"refine init: not a git repository: {client_repo}\n"
            "  Run `git init` inside it first, or pass a path to an existing git repo.",
            file=sys.stderr,
        )
        return 1

    target = client_repo / ".refine"
    try:
        cfg_path = config.write_defaults(target, force=args.force)
    except config.ConfigError as e:
        print(f"refine init: {e}", file=sys.stderr)
        return 1

    # When running from a refine source dir (i.e., the dir containing
    # pyproject.toml and the `refine` package), write a binding + .env so
    # subsequent commands target this client without arguments. Detect by
    # presence of pyproject.toml in cwd.
    binding_written = None
    env_written = None
    if _is_refine_source_dir(cwd):
        binding_path = cwd / config.BINDING_FILENAME
        if binding_path.exists() and not args.force:
            print(
                f"refine init: {binding_path} already exists (use --force to rebind)",
                file=sys.stderr,
            )
            return 1
        binding_written = config.write_binding(cwd, client_repo)
        env_written = cwd / ".env"
        env_written.write_text(
            f"# Auto-generated by `refine init`. Read by docker-compose.\n"
            f"REFINE_CLIENT_REFINE_DIR={target}\n",
            encoding="utf-8",
        )

    print(f"Wrote {cfg_path}")
    print(f"Created directories: {target}/run, {target}/gaps")
    if binding_written:
        print(f"Bound this refine source dir → {client_repo}")
        print(f"Wrote {binding_written}")
        print(f"Wrote {env_written}")
    print()
    print("Next steps:")
    if binding_written:
        print(f"  1. uv run refine runner          # in one terminal (from {cwd})")
        print(f"  2. docker compose up              # in another (from {cwd})")
        print(f"  3. uv run refine doctor           # whenever something looks off")
    else:
        print(f"  1. cd {client_repo}")
        print(f"  2. refine runner                  # in one terminal")
        print(f"  3. docker compose up              # in another")
        print(f"  4. refine doctor                  # whenever something looks off")
    return 0


def _is_refine_source_dir(p: Path) -> bool:
    """Heuristic: cwd is a refine source dir if it has pyproject.toml and a `refine/` package."""
    return (p / "pyproject.toml").is_file() and (p / "refine" / "cli.py").is_file()


# ----- runner -----------------------------------------------------------------

def cmd_runner(args: argparse.Namespace) -> int:
    _load_config_or_exit(args)
    cfg = config.get()

    if args.foreground:
        from refine_runner.__main__ import main as runner_main
        return runner_main()

    pid_path = _runner_pid_path(cfg)
    log_path = _runner_log_path(cfg)

    existing_pid = _read_pid(pid_path)
    if existing_pid is not None and _pid_alive(existing_pid):
        print(
            f"refine runner: already running (pid {existing_pid}).\n"
            f"  socket: {cfg.runner_socket}\n"
            f"  logs:   {log_path}\n"
            f"  stop:   kill {existing_pid}",
            file=sys.stderr,
        )
        return 1
    if existing_pid is not None and not _pid_alive(existing_pid):
        try:
            pid_path.unlink()
        except FileNotFoundError:
            pass

    log_path.parent.mkdir(parents=True, exist_ok=True)

    pid = os.fork()
    if pid > 0:
        # Parent: poll briefly for the socket file (= daemon is listening).
        # Surface a crash if the child dies before binding.
        import time
        deadline = time.time() + 5.0
        bound = False
        while time.time() < deadline:
            if not _pid_alive(pid):
                print(
                    f"refine runner: child {pid} exited before binding the socket. "
                    f"See {log_path}.",
                    file=sys.stderr,
                )
                return 1
            if cfg.runner_socket.exists():
                bound = True
                break
            time.sleep(0.1)
        if not bound:
            print(
                f"refine runner: child {pid} alive but socket did not appear within 5s. "
                f"See {log_path}.",
                file=sys.stderr,
            )
            return 1
        print(f"refine runner started (pid {pid})")
        print(f"  socket: {cfg.runner_socket}")
        print(f"  logs:   {log_path}")
        print(f"  stop:   kill {pid}")
        return 0

    # --- Child: detach from controlling terminal, redirect I/O, run the daemon.
    import signal
    os.setsid()
    log_fd = os.open(str(log_path), os.O_WRONLY | os.O_CREAT | os.O_APPEND, 0o644)
    devnull_fd = os.open(os.devnull, os.O_RDONLY)
    os.dup2(log_fd, 1)        # stdout → log file
    os.dup2(log_fd, 2)        # stderr → log file
    os.dup2(devnull_fd, 0)    # stdin  → /dev/null
    os.close(log_fd)
    os.close(devnull_fd)

    pid_path.write_text(f"{os.getpid()}\n")

    def _cleanup_pid_file(*_a):
        try:
            pid_path.unlink()
        except FileNotFoundError:
            pass

    import atexit
    atexit.register(_cleanup_pid_file)

    from refine_runner.__main__ import main as runner_main
    sys.exit(runner_main())


def cmd_stop(args: argparse.Namespace) -> int:
    import signal
    import time

    _load_config_or_exit(args)
    cfg = config.get()
    pid_path = _runner_pid_path(cfg)

    pid = _read_pid(pid_path)
    if pid is None:
        # No pidfile — but the socket might be live from an older process
        # that didn't write one. Tell the user what we see.
        if cfg.runner_socket.exists():
            print(
                f"refine stop: no {pid_path} but socket {cfg.runner_socket} "
                f"exists. The runner was probably started another way; stop "
                f"it manually.",
                file=sys.stderr,
            )
            return 1
        print("refine stop: no runner is running (no pidfile, no socket).")
        return 0
    if not _pid_alive(pid):
        print(f"refine stop: stale pidfile (pid {pid} is not running); removing.")
        try:
            pid_path.unlink()
        except FileNotFoundError:
            pass
        return 0

    sig = signal.SIGKILL if args.force else signal.SIGTERM
    sig_name = "SIGKILL" if args.force else "SIGTERM"
    try:
        os.kill(pid, sig)
    except PermissionError:
        print(
            f"refine stop: pid {pid} is not owned by this user. "
            f"Try sudo or run as the user that started the runner.",
            file=sys.stderr,
        )
        return 1
    except ProcessLookupError:
        print(f"refine stop: pid {pid} disappeared before signal landed.")
        try:
            pid_path.unlink()
        except FileNotFoundError:
            pass
        return 0
    print(f"refine stop: sent {sig_name} to pid {pid}; waiting up to {args.timeout:.0f}s…")

    deadline = time.time() + args.timeout
    while time.time() < deadline:
        if not _pid_alive(pid):
            print(f"refine stop: pid {pid} exited cleanly.")
            try:
                pid_path.unlink()
            except FileNotFoundError:
                pass
            return 0
        time.sleep(0.1)

    if args.force:
        # Already sent SIGKILL; nothing else to escalate to.
        print(f"refine stop: pid {pid} still alive after SIGKILL — giving up.",
              file=sys.stderr)
        return 1

    print(f"refine stop: pid {pid} did not exit after SIGTERM; escalating to SIGKILL.")
    try:
        os.kill(pid, signal.SIGKILL)
    except ProcessLookupError:
        pass
    # Short wait after SIGKILL to confirm.
    deadline = time.time() + 3.0
    while time.time() < deadline:
        if not _pid_alive(pid):
            try:
                pid_path.unlink()
            except FileNotFoundError:
                pass
            print(f"refine stop: pid {pid} killed.")
            return 0
        time.sleep(0.1)
    print(f"refine stop: pid {pid} still alive after SIGKILL.", file=sys.stderr)
    return 1


def _runner_state_dir(cfg: "config.Config") -> Path:
    """Where to keep the runner pidfile and log file.

    Prefer the refine source dir (the directory containing `.refine-binding`,
    typically the user's refine clone). The bound client's `.refine/` lives
    inside a bind-mounted volume that's exposed to the webapp container — and
    daemon state shouldn't leak in there. Fall back to the volume root when
    no binding is in scope (the inside-client-repo workflow).
    """
    binding = config.find_binding()
    if binding is not None:
        d = binding.parent / "run"
    else:
        d = cfg.volume_root / "run"
    d.mkdir(parents=True, exist_ok=True)
    return d


def _runner_pid_path(cfg: "config.Config") -> Path:
    return _runner_state_dir(cfg) / "runner.pid"


def _runner_log_path(cfg: "config.Config") -> Path:
    return _runner_state_dir(cfg) / "runner.log"


def _read_pid(p: Path) -> int | None:
    try:
        return int(p.read_text().strip())
    except (FileNotFoundError, ValueError):
        return None


def _pid_alive(pid: int) -> bool:
    try:
        os.kill(pid, 0)
        return True
    except ProcessLookupError:
        return False
    except PermissionError:
        # Process exists; we just don't own it.
        return True


# ----- web --------------------------------------------------------------------

def cmd_web(args: argparse.Namespace) -> int:
    _load_config_or_exit(args)
    from refine_web.__main__ import main as web_main
    return web_main()


# ----- doctor -----------------------------------------------------------------

def cmd_doctor(args: argparse.Namespace) -> int:
    cfg_path = args.config
    try:
        cfg = config.get(path=cfg_path) if cfg_path else config.get()
    except config.ConfigError as e:
        print(_red("No refine configuration found."))
        print(f"  {e}")
        print()
        print("Run `refine init` in the client repo to create one.")
        return 1

    print(_section("Configuration"))
    _kv("config file",   cfg.config_path)
    _kv("volume root",   cfg.volume_root)
    _kv("client repo",   cfg.client_repo)
    _kv("runner socket", cfg.runner_socket)
    _kv("web host:port", f"{cfg.web_host}:{cfg.web_port}")

    print(_section("Volume root"))
    sqlite_present = cfg.sqlite_path.is_file()
    _kv("index.sqlite",  f"{cfg.sqlite_path} ({'present' if sqlite_present else 'missing'})")
    gap_count = _count_gap_files(cfg.gaps_dir)
    _kv("gaps/ files",   f"{gap_count} gap.json file(s)")
    _kv("runner socket dir", cfg.runner_socket.parent)

    print(_section("Host runner"))
    reachable, ping_msg = _ipc_ping(cfg.runner_socket)
    _kv("socket reachable", _bool(reachable))
    if not reachable:
        _kv("error", ping_msg or "")
    else:
        _kv("ping ok", "pong")

    print(_section("Claude CLI"))
    claude_path = shutil.which("claude") or "(not on PATH)"
    _kv("claude path", claude_path)
    ok, msg = _claude_version(claude_path)
    _kv("claude --version", _bool(ok))
    if not ok:
        _kv("error", msg or "")

    print(_section("Client repo / git"))
    repo = cfg.client_repo
    if not (repo / ".git").exists():
        _kv("git", _red("not a git repository"))
    else:
        branch = _git(repo, "symbolic-ref", "--quiet", "--short", "HEAD")
        upstream = _git(repo, "rev-parse", "--abbrev-ref", f"{branch.strip()}@{{upstream}}") if branch.strip() else None
        dirty = _git(repo, "status", "--porcelain")
        _kv("branch", branch.strip() or _red("detached HEAD"))
        _kv("upstream", (upstream or "").strip() or _red("no upstream"))
        _kv("clean", _bool(not (dirty or "").strip()))

    print()
    ok_all = reachable and ok and (repo / ".git").exists()
    print(_green("doctor: ok") if ok_all else _red("doctor: issues to address (see above)"))
    return 0 if ok_all else 1


# ----- helpers ----------------------------------------------------------------

def _load_config_or_exit(args: argparse.Namespace) -> None:
    try:
        if args.config:
            config.get(path=args.config)
        else:
            config.get()
    except config.ConfigError as e:
        print(f"refine: {e}", file=sys.stderr)
        sys.exit(1)


def _ipc_ping(socket_path: Path) -> tuple[bool, str | None]:
    if not socket_path.exists():
        return False, f"socket file not found: {socket_path}"
    try:
        with socket.socket(socket.AF_UNIX, socket.SOCK_STREAM) as s:
            s.settimeout(3.0)
            s.connect(str(socket_path))
            envelope = {"id": "doctor", "method": "ping", "params": {}}
            s.sendall((json.dumps(envelope) + "\n").encode("utf-8"))
            buf = b""
            while b"\n" not in buf:
                chunk = s.recv(65536)
                if not chunk:
                    break
                buf += chunk
        line, _, _ = buf.partition(b"\n")
        resp = json.loads(line.decode("utf-8"))
        if resp.get("ok") and resp.get("result", {}).get("pong"):
            return True, None
        return False, f"unexpected response: {resp}"
    except (ConnectionRefusedError, PermissionError, FileNotFoundError) as e:
        return False, repr(e)
    except Exception as e:
        return False, repr(e)


def _claude_version(claude_path: str) -> tuple[bool, str | None]:
    try:
        out = subprocess.run(
            [claude_path, "--version"],
            capture_output=True, text=True, timeout=10,
        )
        if out.returncode == 0:
            return True, out.stdout.strip()
        return False, (out.stderr.strip() or out.stdout.strip()
                       or f"exit code {out.returncode}")
    except FileNotFoundError as e:
        return False, repr(e)
    except subprocess.TimeoutExpired:
        return False, "claude --version timed out (10s)"
    except Exception as e:
        return False, repr(e)


def _git(cwd: Path, *args: str) -> str:
    try:
        out = subprocess.run(
            ["git", *args], cwd=str(cwd),
            capture_output=True, text=True, timeout=10,
        )
        return out.stdout
    except Exception:
        return ""


def _count_gap_files(gaps_dir: Path) -> int:
    if not gaps_dir.is_dir():
        return 0
    return sum(1 for _ in gaps_dir.rglob("gap.json"))


def _section(title: str) -> str:
    return f"\n{_bold(title)}\n" + "-" * len(title)


def _kv(label: str, value) -> None:  # noqa: ANN001
    print(f"  {label:<22} {value}")


def _bool(b: bool) -> str:
    return _green("yes") if b else _red("no")


def _bold(s: str) -> str:
    return f"\033[1m{s}\033[0m" if sys.stdout.isatty() else s


def _red(s: str) -> str:
    return f"\033[31m{s}\033[0m" if sys.stdout.isatty() else s


def _green(s: str) -> str:
    return f"\033[32m{s}\033[0m" if sys.stdout.isatty() else s
